### ISSUE TITLE
getting invalid distance too far back error

### ISSUE THREAD

**Issue by Androz2091** [technikhil314/offline-diff-viewer#135]
https://diffviewer.vercel.app/v1/diff#H4sIAAAAAAAAA6WVTY/aMBCG/8o0J6JmIa3UHpalUtVrvyTaXghCTjIm1gab2g7LarX/vU5im6wJ3VXLicw7Hr/zZOw8RCWjNLperdIkog0vNBMctCRcUZQTUpYSlYKNFgk0jOu3797D5kDqBmOI1snq6k0SPWQy492Tedg3ec2K9sEUdEGJupFcBdFJLkQdB8GHjLuI+fn1vxsbZW5XehKtNDEuvamFVV9ZceGV9Ggl29zEZqSxywBdSXE3h7/ZjNbJwlayCIb+C7xgFx7nGD8pccU7MZT+KkQckNmEgPjSiMpnYVM+mLx3JbryXSqzrTVWycvxdO9N8/hxiH64PynTorHOmuFHoy39qstGOa002Azdo3SAZwcg8BWItEog6iuCA9CaYviP6YjJzXhBX6jq53aThXyEuX6RMPBWLgNelweyflQzGbwqcLiFhg1Il5ipjyupZW6rZ3BUqACLjRYsSLhwoNHhlw02yoEPaTb9zhK6qqfln+FZg7XGl5DOERn2J6uCPFdgmRYhqenZ0uFBHFASWtxp152Ogaj8QTC+AAsYEkofiG6mirzZ9nk45OSuHtvPtxn5FYAU8Kc+EIDlWLXTgb0JTJ50eqZw452YO1jWQbv4xlPYxBGEo1lU9oYdePpcxSxoZ0LYXuHtS1JLMLx2TN0O+nhjA7ctCZ+uI/LCW7Sf2CGzXS+n3Nu3X8VmtF7IPxeuJtHnvVSMxWaQ85seuPy/ZvZmi6Juborv8xc405sG3Arw43aW17cwr4m5hy6Ob08pCb4GK3XSVRX6jPJsY6uo735bjDRqE0hSpwqUZvzIk8yYRvKjlie5Mc/5FfrIccHAAA=

**Comment by technikhil314** [comment]
This is no longer valid in v2 links hence closing this. thanks.
