### ISSUE TITLE
How's the matching working?

### ISSUE THREAD

**Issue by rew1nter** [technikhil314/offline-diff-viewer#136]
![image](https://github.com/technikhil314/offline-diff-viewer/assets/64508791/b31da47c-80c9-408a-99a8-69768f252712)
Why's line 7,8,9 not in red here? Those texts were removed :/

**Comment by technikhil314** [comment]
can you share the link to the diff please @rew1nter?

**Comment by rew1nter** [comment]
nope. The problem is pretty visible in the code and you can write some mock data to test it. 

line 7,8,9 on the left were removed but aren't in red

**Comment by rew1nter** [comment]
You may use [this](https://www.diffchecker.com/) site for reference

**Comment by technikhil314** [comment]
Fixed. in version [v0.7.0](https://github.com/technikhil314/offline-diff-viewer/releases/tag/v0.7.0)
