### ISSUE TITLE
Provide option to Donate to support the project

### ISSUE THREAD

**Issue by RaheelJameel** [technikhil314/offline-diff-viewer#177]
Open Source Software is not free from the point of view of the perople behind it. At the very least it takes up their spare time to work on them, the time which can be spent elsewhere to earn money. Time is money.
So projects which we find value in should be supported.

Kindly setup a way to receive donations on any platform of your choice for example: https://opencollective.com/ , https://ko-fi.com/ , https://www.patreon.com/ or any other.

Hard work should be rewarded.

**Comment by technikhil314** [comment]
Sure will add links to the page. meanwhile feel free to donate via github sponsors link https://github.com/sponsors/technikhil314
